### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by PrathameshAdate05** [massivemadness/Squircle-IDE#100]
*Please consider making a Pull Request if you are capable of doing so.*

**App Version:**
2020.x.x Standard Edition

**Affected Device(s):**
Google Pixel 3 XL with Android 9.0

**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Comment by massivemadness** [comment]
Hi @PrathameshAdate05, is there any details? 🤔

**Comment by PrathameshAdate05** [comment]
it was not showing line numbers and black theme in background

**Comment by massivemadness** [comment]
@PrathameshAdate05 I need more info, steps to reproduce would help a lot
