### ISSUE TITLE
Auto close brackets/parentheses

### ISSUE THREAD

**Issue by lamideag** [massivemadness/Squircle-IDE#101]
I want to know how to close the parentheses in writing the code. I searched a lot, but to no avail. Here is the link to the question.
https://stackoverflow.com/questions/69721789/how-complete-the-closing-of-the-parentheses-in-edit-text-kotlin

**Comment by massivemadness** [comment]
Please have a look at the [instructions](https://github.com/massivemadness/Squircle-IDE#configuration).
```kotlin
val pluginSupplier = PluginSupplier.create {
    autoIndentation {
        autoIndentLines = true // whether the auto indentation enabled
        autoCloseBrackets = true // automatically close open parenthesis/bracket/brace
        autoCloseQuotes = true // automatically close single/double quote when typing
    }
}
editor.plugins(pluginSupplier)
```
