### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by TimScriptov** [massivemadness/Squircle-IDE#102]
When scrolling through the code, the code moves down

![Screenshot_20211107_184748_com.blacksquircle.ui.jpg](https://user-images.githubusercontent.com/31324315/140647801-5b9d0596-bc6e-4532-9eec-81d8881dd994.jpg)

**Comment by massivemadness** [comment]
@TimScriptov привет, можешь проверить исправлен-ли баг в `develop`? На моём устройстве всё ок

**Comment by TimScriptov** [comment]
@massivemadness привет, нет возможности сейчас собрать исходный код

**Comment by massivemadness** [comment]
окей, тогда на днях ещё потестирую и если всё ок то обновлю в play store 👌

**Comment by TimScriptov** [comment]
Ошибку больше не наблюдаю
