### ISSUE TITLE
The sign '-' display differently in different positions

### ISSUE THREAD

**Issue by LaunchLee** [massivemadness/Squircle-IDE#106]
*Please consider making a Pull Request if you are capable of doing so.*

**App Version:**
2020.1.4 Standard Edition (2021.11.14 update)

**Affected Device(s):**
Redmi 9 with MIUI 12.5.3 (Android 11.0)

**Describe the bug**
![IMG_20211126_214734](https://user-images.githubusercontent.com/80872691/143590586-01753a9a-3d52-43a6-b07a-7eccf58dbb49.jpg)

**To Reproduce**
1. Input '-' after character(s) that is(are) not English (or ASCII char).

**Expected behavior**
'-' is displayed in the same size.

**Comment by massivemadness** [comment]
That's the internal `TextView` behavior, so I can't fix that 😔
