### ISSUE TITLE
Minor translation mistakes

### ISSUE THREAD

**Issue by Heromaex** [massivemadness/Squircle-IDE#109]
**App Version:**
2021.1.4 (10008)

**Affected Device(s):**
LG Velvet with Android 11.0

**Describe the bug**
Just some minor spelling issues in **german** translation. I decided to report this and you can handle that however you want to

1. gewechse~~k~~t -> gewechse**l**t
![Screenshots_2022-02-01-23-54-11.png](https://user-images.githubusercontent.com/71891972/152066400-860bf1e4-af30-4148-b075-702e65690f44.png)

2. übersetz~~t~~en -> übersetzen
![Screenshots_2022-02-01-23-59-31.png](https://user-images.githubusercontent.com/71891972/152066522-737a3c4e-1985-473d-9d22-60e893a47f7c.png)

**To Reproduce**
1. switch to german language
2. open settings (einstellungen)
3. open über (about)

**Comment by Heromaex** [comment]
Well its not a bug but idk how to add labels on the mobile app and I took a template lol

**Comment by massivemadness** [comment]
Sorry, I forgot to fix it in yesterday's update
