### ISSUE TITLE
Type Mismatch Error

### ISSUE THREAD

**Issue by arsalan1212** [massivemadness/Squircle-IDE#112]
While setting editor language getting Type mismatch error. Checkout the attached screenshot

![Type mismatch](https://user-images.githubusercontent.com/28539076/154210934-e547a264-a6db-482e-8439-527f7ddbd4aa.png)

**Comment by massivemadness** [comment]
Hi @arsalan1212 , what libraries did you add? It should be `com.blacksquircle.ui:editorkit` and `com.blacksquircle.ui:language-json` right?

**Comment by massivemadness** [comment]
Just reproduced it on a new project ☹️ 
I'll fix this within a few days, but right now you can use v2.0.0, it works well

**Comment by massivemadness** [comment]
Fixed in v2.1.2 (f02741bc1dd92a9f44f23f55a4dac0a00c237eac).
Thanks for reporting, there was just a typo in upload script
