### ISSUE TITLE
Why does this app looks like Java N Ide?

### ISSUE THREAD

**Issue by PranavPurwar** [massivemadness/Squircle-IDE#118]
Was it's style copied? If yes, then please atleast credit it.

**Comment by massivemadness** [comment]
Hi @PranavPurwar, I don't see any coincidences in terms of look and feel, it's totally different to me.
The "Material Design" is a common design system in android development

**Comment by PranavPurwar** [comment]
![Screenshot_2022-03-15-17-03-55](https://user-images.githubusercontent.com/75154889/158369751-3842154a-53bd-40c9-8efb-e6ece69f5af4.png)
![Screenshot_2022-03-15-17-05-49](https://user-images.githubusercontent.com/75154889/158369773-1549e9ea-947d-4da1-8a3c-b8991811a823.png)
see above, the app's theme is almost the same, with some minor improvements (in look). Anyways i don't have any problem with it because the project got abandoned. Sorry if i sounded rude

**Comment by CodeCrazy-ywt** [comment]
No, they are quite different

**Comment by PranavPurwar** [comment]
i didn't ask
