### ISSUE TITLE
Smali, gradle language 

### ISSUE THREAD

**Issue by TimScriptov** [massivemadness/Squircle-IDE#124]
Hi. Please add code highlighting for smali and gradle

**Comment by TimScriptov** [comment]
Также скролл кода конфликтует с курсором. Чтобы пролистать код, нужно сначала свайпнуть вверх или вниз, а затем в сторону

**Comment by TimScriptov** [comment]
Также выделение строки где находится курсор работает не правильно. Он выделяет несколько строк

**Comment by TimScriptov** [comment]
Также двойной перенос не исправлен

**Comment by TimScriptov** [comment]
Также не работает интент. В телеграм жму на файл, система предлагает через какой редактор открыть файл. Жму на Squircle-IDE, она пишет "Файл не найден"

**Comment by massivemadness** [comment]
@TimScriptov 
1) Если нужна простая подсветка то это не долго делается
2) Если включен горизонтальный скролл, то это стандартное поведение едиттекста, тут ничего не поделать
3) Если включен перенос строк, то это не баг а фича :) выделяется строка текста, а не строка текстового поля
4) Можешь видео прислать? Не хватает подробностей
5) В последнем обновлении поправил, сейчас на модерации в магазине

**Comment by TimScriptov** [comment]
> @TimScriptov 
> 1) Если нужна простая подсветка то это не долго делается
> 2) Если включен горизонтальный скролл, то это стандартное поведение едиттекста, тут ничего не поделать
> 3) Если включен перенос строк, то это не баг а фича :) выделяется строка текста, а не строка текстового поля
> 4) Можешь видео прислать? Не хватает подробностей
> 5) В последнем обновлении поправил, сейчас на модерации в магазине
> 

Ок будет время запишу видео

**Comment by TimScriptov** [comment]
https://youtu.be/P1PobmOje1M

**Comment by massivemadness** [comment]
gradle f1bcb68056eb22dfe99caba106b9c1e7d8dc703e
smali 54ef0fe8702b5ae9788ef557ce5c349c1c58c47c
