### ISSUE TITLE
TAB issue in Samsung DEX with hardware keyboard

### ISSUE THREAD

**Issue by FueLee** [massivemadness/Squircle-IDE#131]
**Description:**

I am using the app on my Samsung Galaxy S22 in Samsung DEX station with an USB keyboard.

When the focus is in the editor area and I press TAB key on the hardware keyboard, the focus will be on another screen element of the app and the TAB (4 or 8 spaces) will not be inserted into the text. Of course, I can hit space key 4 times and it inserts it.

Can you check please?

**App Version:**
2022.1.1 (10010)

**Affected Device(s):**
Samsung Galaxy S22 in Samsung DEX station

**To Reproduce**
1. Create a new file (example.c)
2. Start editing the file
3. hit TAB key to insert 4 space character

**Expected behavior**
The preconfigured number of spaces are inserted into the text.

**Comment by massivemadness** [comment]
Thanks for reporting, that's known issue https://github.com/massivemadness/Squircle-IDE/issues/85, I'll fix it in the next update

**Comment by massivemadness** [comment]
261b9d7fd3f9cf4f63fe7469a4373227b2ae4892
