### ISSUE TITLE
Create new file, read-only mode

### ISSUE THREAD

**Issue by aDifferentBook** [massivemadness/Squircle-IDE#45]
*Please consider making a Pull Request if you are capable of doing so.*

**Is your feature request related to a problem? Please describe.**
1. Currently we need to create a new file from navigation bar but it's very frustrating and time consuming.
2. Read-only mode is missing

**Describe the solution you'd like**
1. Add **+ button** at top toolbar to **create new file** and **save button** to quick save file while we're working. Also after closing all files an empty file must be there like other editors.

2. Read-only mode is self explanatory.

**Describe alternatives you've considered**
Add these options at top toolbar.

**Additional context**
None

**Comment by massivemadness** [comment]
I've never seen anyone using readonly mode 🙂

**Comment by aDifferentBook** [comment]
I'm learning coding on mobile and don't have PC so sometimes while scrolling long file I accidentally add some random words to file so it's helpful if read-only mode is available.
