### ISSUE TITLE
Modernize Logo

### ISSUE THREAD

**Issue by corobin** [massivemadness/Squircle-IDE#50]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
The logo looks a little out of place between other android icons,

If there is appetite for updating the android app icon i would suggest bringing it in line with current material style. for the current logo i would roughly observe: remove flourish on the brackets, less heavy shadows, simpler gradient

I did a [quick mockup using the current colour scheme](https://github.com/massivemadness/Brackeys-IDE/files/6168098/Brackeys.zip) just to illustrate what it might look like, but i'm not suggesting using this verbatim. i'm sure someone with more skills than me can do much better.

just a thought.

**Comment by massivemadness** [comment]
Hi, thanks for contribution! I like the idea but the icon looks "oversimplified" to me 🤷‍♂️
I'll leave this issue open (maybe somebody send a better version later), but right now I prefer the current icon.
