### ISSUE TITLE
Support "Tab" key on soft keyboard

### ISSUE THREAD

**Issue by errr-maxx** [massivemadness/Squircle-IDE#73]
**Is your feature request related to a problem? Please describe.**
I have Full Keyboard (Hacker's keyboard fork) installed on my device, both of them have "Tab" key, but that key don't work properly in Brackeys IDE (It focuses other app interface elements)

**Describe the solution you'd like**
When you press "Tab" button, it must insert tabulation/spaces (according to settings) into the code

**Comment by nevdelap** [comment]
I am using a bluetooth keyboard and tabbing in the code editor moves focus to the hamburger menu, then to the file menu, the edit menu, the undo, etc, to the editor tab and then back and forth between the tab and the tab's close button. I had thought it made the editor unusable for coding, but there is a work around, shift+tab behaves as tab.

**Comment by errr-maxx** [comment]
Fixed in https://github.com/massivemadness/Squircle-IDE/commit/261b9d7fd3f9cf4f63fe7469a4373227b2ae4892. Thanks!
