### ISSUE TITLE
tab on hardware keyboard doesn't work

### ISSUE THREAD

**Issue by WulftheNordicRanger** [massivemadness/Squircle-IDE#85]
Rather than inserting a tab, pressing the tab key makes the cursor disappear.

**Comment by Timerix22** [comment]
just press ctrl+tab

**Comment by nevdelap** [comment]
shift+tab also functions as tab.

**Comment by massivemadness** [comment]
261b9d7fd3f9cf4f63fe7469a4373227b2ae4892
