### ISSUE TITLE
Plagiarism

### ISSUE THREAD

**Issue by sheep8898** [massivemadness/Squircle-IDE#93]
There is a plagiarism here, just changed the logo. https://play.google.com/store/apps/details?id=lk.visual.code.mobile 

The picture on Google play is not real, you should download it and take a look. 

He even added advertisements in the software to charge.

**Comment by massivemadness** [comment]
Hi @du-wen-xuan, like I said earlier, I checked it and there is no plagiarism to me. It's completely different application

**Comment by Gugui322** [comment]
> Hi @du-wen-xuan, like I said earlier, I checked it and there is no plagiarism to me. It's completely different application

![Screenshot_20211112-103632.png](https://user-images.githubusercontent.com/65572156/141475755-1536e8d4-2767-4e30-b33f-31cb40df5e4c.png)

Not sure but this use the IDE source code.

**Comment by massivemadness** [comment]
@Gugui322 ok now I see, there was a completely different app before
