### ISSUE TITLE
when use language-html do not show me the suggestions

### ISSUE THREAD

**Issue by lamideag** [massivemadness/Squircle-IDE#99]
Is there a solution to this problem?

**Comment by massivemadness** [comment]
Hi @lamideag, you can [access](https://github.com/massivemadness/Squircle-IDE/blob/master/editorkit/src/main/kotlin/com/blacksquircle/ui/editorkit/plugin/autocomplete/Actions.kt#L22) the `suggestionAdapter` and set it to `null` only for html language.  
I would write something like this (not the best solution, but it works)
```kotlin
viewModel.languageLiveData.observe(this) { lang ->
    editor.language = lang
    if (lang.getName() == "html") {
        editor.suggestionAdapter = null
    } else {
        editor.suggestionAdapter = *change it back to your adapter*
    }
}
```
Is that what you were looking for? 🤔
